spring:
  application:
    name: servidor-gateway
  cloud:
    gateway:      routes:      - id: service-transations
        uri: lb://service-transations
        predicates:         - Path=/api/transaction/**
        filters:          - StripPrefix=2
      - id: service-customer
        uri: lb://service-customer
        predicates:
         - Path=/api/costumer/**
        filters:
          - StripPrefix=2      
      - id: service-products
        uri: lb://service-products
        predicates:
         - Path=/api/products/**
        filters:
          - StripPrefix=2      discovery:        locator:          enabled: true
      
server:  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
